package logisticsapp.commands.enums;

public enum CommandType {
    CREATEDELIVERYPACKAGE,
    CREATECUSTOMER,
    CREATETRUCK,
    CREATEDELIVERYROUTE,
    CREATELOCATION,
    ASSIGNPACKAGE,
    ASSIGNTRUCK,
    ASSIGNCUSTOMERTOPACKAGE,
    SEARCHROUTE,
    STARTROUTE,
    HELP,
    SHOWROUTES,
    SHOWUNASSIGNEDPACKAGES


}
